### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by piever** [piever/Recombinase.jl#7]
To do list:

- [x] Choose colormap (wong?) and set color to black when color is not a grouping attribute
- [x] Add `axis_style` keyword to analysis and split in "continuous" versus "discrete" (`prediction`, `distribution`, `cumulative`, `hazard`) (done with `discrete` function)
- [x] clean up automatic axis selection (no hack for density)
- [x] Add documentation
- [x] Add tests
- [x] Less DWIM across behavior (and easy way to select `none` or `all`).
- [x] Support for ShiftedArrays
- [x] Name the package
- [x] Remame across (to by or error)
- [x] Add axis type "array" for plot of array of arrays
- [x] Finalize `estimator` and `confidence` API (see https://github.com/piever/Recombinase.jl/pull/17)
